// auth
export const SIGNUP_PENDING = 'SIGNUP_PENDING'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_PENDING = 'LOGOUT_PENDING'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

// user
export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'
export const FETCH_CURRENT_USER_PENDING = 'FETCH_CURRENT_USER_PENDING'
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS'
export const FETCH_CURRENT_USER_FAILURE = 'FETCH_CURRENT_USER_FAILURE'
export const SAVE_USER_PENDING = 'SAVE_USER_PENDING'
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS'
export const SAVE_USER_FAILURE = 'SAVE_USER_FAILURE'

// friend
export const FETCH_FRIENDS_PENDING = 'FETCH_FRIENDS_PENDING'
export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS'
export const FETCH_FRIENDS_FAILURE = 'FETCH_FRIENDS_FAILURE'
export const FETCH_FRIEND_REQUESTS_PENDING = 'FETCH_FRIEND_REQUESTS_PENDING'
export const FETCH_FRIEND_REQUESTS_SUCCESS = 'FETCH_FRIEND_REQUESTS_SUCCESS'
export const FETCH_FRIEND_REQUESTS_FAILURE = 'FETCH_FRIEND_REQUESTS_FAILURE'
export const FETCH_FRIEND_CONFIRMATIONS_PENDING =
  'FETCH_FRIEND_CONFIRMATIONS_PENDING'
export const FETCH_FRIEND_CONFIRMATIONS_SUCCESS =
  'FETCH_FRIEND_CONFIRMATIONS_SUCCESS'
export const FETCH_FRIEND_CONFIRMATIONS_FAILURE =
  'FETCH_FRIEND_CONFIRMATIONS_FAILURE'
export const REQUEST_FRIEND_PENDING = 'REQUEST_FRIEND_PENDING'
export const REQUEST_FRIEND_SUCCESS = 'REQUEST_FRIEND_SUCCESS'
export const REQUEST_FRIEND_FAILURE = 'REQUEST_FRIEND_FAILURE'
export const CONFIRM_FRIEND_PENDING = 'CONFIRM_FRIEND_PENDING'
export const CONFIRM_FRIEND_SUCCESS = 'CONFIRM_FRIEND_SUCCESS'
export const CONFIRM_FRIEND_FAILURE = 'CONFIRM_FRIEND_FAILURE'
